### ISSUE TITLE
How to convert the RAFT repo's pth into onnx model

### ISSUE THREAD

**Issue by qihao-plus** [ibaiGorordo/ONNX-RAFT-Optical-Flow-Estimation#1]
Thanks for your providing onnx model for onnx runtime inference.
I'm wondering how you export the [RAFT pth model ](https://github.com/princeton-vl/RAFT#demos) into onnx model without GridSampler and Correlation ops. 

Thanks!

**Comment by qihao-plus** [comment]
It looks like the tool [openvino2tensorflow](https://github.com/PINTO0309/openvino2tensorflow#openvino2tensorflow) you provided is not related with the above operations.

**Comment by ibaiGorordo** [comment]
Start from the demo.py in the original repository, and at the end, add the model conversion as in (https://pytorch.org/tutorials/advanced/super_resolution_with_onnxruntime.html), replacing some of the options. 
```
# Input to the model
x = torch.randn(batch_size, 1, 224, 224, requires_grad=True)
torch_out = torch_model(x)

# Export the model
torch.onnx.export(torch_model,               # model being run
                  x,                         # model input (or a tuple for multiple inputs)
                  "super_resolution.onnx",   # where to save the model (can be a file or file-like object)
                  export_params=True,        # store the trained parameter weights inside the model file
                  opset_version=10,          # the ONNX version to export the model to
                  do_constant_folding=True,  # whether to execute constant folding for optimization
                  input_names = ['input'],   # the model's input names
                  output_names = ['output'], # the model's output names
                  dynamic_axes={'input' : {0 : 'batch_size'},    # variable length axes
                                'output' : {0 : 'batch_size'}})
```

**Comment by qihao-plus** [comment]
Thanks for you quick reply.
Here is my result using PyTorch 1.6.0
If you do not use onnx surgen and TensorRT plugin, how you replace those ops to get 'raft_kitti_iter10_480x640.onnx' in this repo ?
![Screenshot from 2022-08-30 18-00-25](https://user-images.githubusercontent.com/93700759/187408797-b05de79c-83c5-4b30-b4ca-2409f951ed7b.png)

**Comment by ibaiGorordo** [comment]
There are ways to replace grid_sample in Pytorch but that is not necessary anymore. Make sure you have Pytorch 1.12 and change the opset_version to 16.

**Comment by qihao-plus** [comment]
![Screenshot from 2022-08-30 18-06-14](https://user-images.githubusercontent.com/93700759/187410007-d81a118c-6c95-4866-ac36-89732e4a00ec.png)
But the onnx model you provided is PyTorch 1.10 and opset 11 ?

**Comment by ibaiGorordo** [comment]
Yes, the old way was to replace grid sample in Pytorch with a custom function, but it has been recently supported so that trick is not necessary anymore

**Comment by qihao-plus** [comment]
Thanks for you advice.

**Comment by qihao-plus** [comment]
Thanks for your advice.
Although GridSample is supported in ONNX opset 16, the latest TRT 8.4 version still does not support GridSample and Corr used in RAFT (supported ops https://github.com/onnx/onnx-tensorrt/blob/main/docs/operators.md)

So, I'm still very curious about how you replace grid sample in Pytorch with a custom function, then get the "pure" RAFT model provided in this repo.

Since I'm trying to export batch inference mode onnx model, so I have to re-export the model instead of using your model directly.

**Comment by ibaiGorordo** [comment]
I see, good to know. Here are some useful links:
- https://github.com/pytorch/pytorch/issues/27212#issuecomment-966334554
- The bilinear grid sampler implementation: https://mmcv.readthedocs.io/en/latest/_modules/mmcv/ops/point_sample.html
- Alternative option: https://zenn.dev/pinto0309/scraps/7d4032067d0160

Replace the bilinear_sampler() calls in the original RAFT model, with the alternative implementation

**Comment by qihao-plus** [comment]
Thanks for your reference links.

I got the following onnx model by replacing `img = F.grid_sample(img, grid, align_corners=True)` into your `def 
bilinear_grid_sample(im, grid, align_corners=False):` .

But, according to https://github.com/pytorch/pytorch/issues/27212#issuecomment-966334554 metioned by you, the F.grid_sample GPU op is replaced by CPU op. The speed is lower than GPU.

Thanks again!

![Screenshot from 2022-08-31 16-40-43](https://user-images.githubusercontent.com/93700759/187636423-b5cf4a53-1c79-4fad-846d-4b004b137b21.png)

**Comment by ibaiGorordo** [comment]
Not sure about the difference in speed. If you want to compare, you can test in onnxruntime the model with opset=16 and the model with the alternative function.

If the speed is significantly slower, you might have to wait for its implementation in TensorRT or use a different model.

**Comment by qihao-plus** [comment]
I make it work in **TensorRT** using PyTorch 1.10, opset 11, and replace RAFT `bilinear_sampler` with the [link](https://zenn.dev/pinto0309/scraps/7d4032067d0160#comment-3291edc6ae396f ) you provided.

BTW, this [fuction](https://zenn.dev/link/comments/5f109cbfc13a25) does not work in trtexec (onnx-> trt engine). 

Also, I found the grid_sampler op will be supported in [TensorRT 8.5 in Q3, 2022](https://github.com/NVIDIA/TensorRT/issues/2005), although it's already supported in ONNX Runtime and ONNX opset 16.

Thanks for your reply and advice again !
